baseurl = "https://clintonbale.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-CA"
layoutdir = "layouts"
publishdir = "public"
author = "Clinton Bale"
title = "Clinton Bale"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Programming Blog and Portfolio"
copyright = "Copyright © 2017 Clinton Bale"
logofile = "images/logo.png"
faviconfile = "images/logo.png"
highlightjs = true
progressively = true
share = true
latestpostcount = 5
github = "clintonbale"
email = "clinton@clintonbale.com"
linkedin = "clintonbale"
twitter = "Clinton_Bale"
social_banner = "images/banner.png"
posts_navigation = true

[params.colors]
#identifier = "#527fc1f"
#identifier_dark = "#1a3152"
foreground = "#181d2a"
#trivial = "#969896"
#background = "#fff"
#background_dark = "#eee"
#code = "#87a5d2"
#type = "#97d28b"
#special = "#ffcb8d"
#value = "#96c2d7"
#statement = "#ff8e91"
