baseurl = "https://clintonbale.com"
DefaultContentLanguage = "en"
title = "Clinton Bale"
theme = "cbhugo"
metaDataFormat = "toml"
disqusShortname = "clintonbale"
googleAnalytics = "UA-52078346-1"
#description = "ass"

[Params]
  subtitle = "Software Developer"
  logo = "images/me.png"
  favicon = "images/favicon.ico"
  dateFormat = "January 2, 2006"
  rss = false
  comments = true
  
[Author]
  name = "Clinton Bale"
  email = "clinton@clintonbale.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "clintonbale"
  twitter = "Clinton_Bale"
  #reddit = "username"
  linkedin = "clintonbale"
  #xing = "username"
  stackoverflow = "users/3011495/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "blog"
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "projects"
    weight = 4

[[menu.main]]
    name = "Maps"
    url = "maps"
    weight = 5

#used for sub-menuing
#[[menu.main]]
#    parent = "samples"
#    name = "Big Image Sample"
#    url = "post/2017-03-07-bigimg-sample"
#    weight = 1
